"""add plant analyses table

Revision ID: 192a81ca81b7
Revises: 870a627640e6
Create Date: 2026-01-05 13:06:15.724856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192a81ca81b7'
down_revision: Union[str, None] = '870a627640e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_analyses',
    sa.Column('user_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('tg_file_id', sa.String(), nullable=False),
    sa.Column('tg_file_unique_id', sa.String(), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_tg_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_analyses_user_tg_id'), 'plant_analyses', ['user_tg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plant_analyses_user_tg_id'), table_name='plant_analyses')
    op.drop_table('plant_analyses')
    # ### end Alembic commands ###
