"""add garden tables

Revision ID: eb266184380d
Revises: b9e8babd1bac
Create Date: 2026-01-29 16:20:52.915107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb266184380d'
down_revision: Union[str, None] = 'b9e8babd1bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garden_plants',
    sa.Column('user_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('watering_interval_days', sa.Integer(), nullable=False),
    sa.Column('last_watered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_watering_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notifications_enabled', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.Column('last_notification_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_tg_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garden_plants_user_tg_id'), 'garden_plants', ['user_tg_id'], unique=False)
    op.create_table('garden_plant_history',
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['garden_plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garden_plant_history_plant_id'), 'garden_plant_history', ['plant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_garden_plant_history_plant_id'), table_name='garden_plant_history')
    op.drop_table('garden_plant_history')
    op.drop_index(op.f('ix_garden_plants_user_tg_id'), table_name='garden_plants')
    op.drop_table('garden_plants')
    # ### end Alembic commands ###
